import { type Project } from '../types/finder'

const showStub = (fileType: string, fileName: string) => {
  alert(`[Заглушка] Открывается ${fileType}: ${fileName}`)
}

export const PROJECTS_DATA: Project[] = [
  {
    id: 'ecommerce',
    name: 'E-commerce Platform',
    type: 'folder',
    icon: '🛒',
    children: [
      {
        id: 'frontend',
        name: 'Frontend',
        type: 'folder',
        icon: '⚛️',
        children: [
          {
            id: 'components',
            name: 'Components',
            type: 'folder',
            icon: '🧩',
            children: [],
          },
          {
            id: 'pages',
            name: 'Pages',
            type: 'folder',
            icon: '📄',
            children: [],
          },
          {
            id: 'utils',
            name: 'Utils',
            type: 'folder',
            icon: '🔧',
            children: [],
          },
          {
            id: 'package-json',
            name: 'Package.json',
            type: 'file',
            icon: '⚙️',
            fileType: 'package',
            action: () => showStub('Configuration', 'Package.json'),
          },
          {
            id: 'build-config',
            name: 'Build Configuration',
            type: 'file',
            icon: '🛠️',
            fileType: 'build',
            action: () => showStub('Configuration', 'Build Configuration'),
          },
          {
            id: 'tests',
            name: 'Tests',
            type: 'file',
            icon: '🧪',
            fileType: 'test',
            action: () => showStub('Test Suite', 'Tests'),
          },
          {
            id: 'deployment',
            name: 'Deployment',
            type: 'file',
            icon: '📦',
            fileType: 'deployment',
            action: () => showStub('Deployment', 'Deployment'),
          },
        ],
      },
      {
        id: 'backend',
        name: 'Backend',
        type: 'folder',
        icon: '🔧',
        children: [
          {
            id: 'api',
            name: 'API',
            type: 'folder',
            icon: '🌐',
            children: [],
          },
          {
            id: 'services',
            name: 'Services',
            type: 'folder',
            icon: '⚙️',
            children: [],
          },
          {
            id: 'middleware',
            name: 'Middleware',
            type: 'folder',
            icon: '🔗',
            children: [],
          },
        ],
      },
      {
        id: 'database',
        name: 'Database',
        type: 'folder',
        icon: '🗄️',
        children: [
          {
            id: 'migrations',
            name: 'Migrations',
            type: 'folder',
            icon: '🔄',
            children: [],
          },
          {
            id: 'seeds',
            name: 'Seeds',
            type: 'folder',
            icon: '🌱',
            children: [],
          },
        ],
      },
      {
        id: 'infrastructure',
        name: 'Infrastructure',
        type: 'folder',
        icon: '🏗️',
        children: [
          {
            id: 'docker',
            name: 'Docker',
            type: 'folder',
            icon: '🐳',
            children: [],
          },
          {
            id: 'aws',
            name: 'AWS',
            type: 'folder',
            icon: '☁️',
            children: [],
          },
        ],
      },
      {
        id: 'github',
        name: 'GitHub Repository',
        type: 'file',
        icon: '👨‍💻',
        fileType: 'github',
        action: () => showStub('GitHub Repository', 'GitHub Repository'),
      },
      {
        id: 'demo',
        name: 'Live Demo',
        type: 'file',
        icon: '🌐',
        fileType: 'demo',
        action: () => showStub('Live Demo', 'Live Demo'),
      },
      {
        id: 'architecture',
        name: 'Architecture Diagram',
        type: 'file',
        icon: '📊',
        fileType: 'diagram',
        action: () => showStub('Architecture Diagram', 'Architecture Diagram'),
      },
      {
        id: 'schema',
        name: 'Database Schema',
        type: 'file',
        icon: '🗃️',
        fileType: 'schema',
        action: () => showStub('Database Schema', 'Database Schema'),
      },
      {
        id: 'docs',
        name: 'Documentation',
        type: 'file',
        icon: '📚',
        fileType: 'docs',
        action: () => showStub('Documentation', 'Documentation'),
      },
      {
        id: 'deployment-guide',
        name: 'Deployment Guide',
        type: 'file',
        icon: '🚀',
        fileType: 'deployment',
        action: () => showStub('Deployment Guide', 'Deployment Guide'),
      },
    ],
  },
  {
    id: 'portfolio',
    name: 'Portfolio Website',
    type: 'folder',
    icon: '💼',
    children: [
      {
        id: 'client',
        name: 'Client',
        type: 'folder',
        icon: '⚛️',
        children: [],
      },
      {
        id: 'server',
        name: 'Server',
        type: 'folder',
        icon: '🔧',
        children: [],
      },
      {
        id: 'design',
        name: 'Design',
        type: 'folder',
        icon: '🎨',
        children: [],
      },
      {
        id: 'github-portfolio',
        name: 'GitHub Repository',
        type: 'file',
        icon: '👨‍💻',
        fileType: 'github',
        action: () => showStub('GitHub Repository', 'Portfolio GitHub'),
      },
      {
        id: 'live-portfolio',
        name: 'Live Website',
        type: 'file',
        icon: '🌐',
        fileType: 'demo',
        action: () => showStub('Live Website', 'Portfolio Live'),
      },
    ],
  },
  {
    id: 'ml-project',
    name: 'ML Project',
    type: 'folder',
    icon: '🤖',
    children: [
      {
        id: 'notebooks',
        name: 'Notebooks',
        type: 'folder',
        icon: '📓',
        children: [],
      },
      {
        id: 'models',
        name: 'Models',
        type: 'folder',
        icon: '🧠',
        children: [],
      },
      {
        id: 'data',
        name: 'Data',
        type: 'folder',
        icon: '📊',
        children: [],
      },
      {
        id: 'github-ml',
        name: 'GitHub Repository',
        type: 'file',
        icon: '👨‍💻',
        fileType: 'github',
        action: () => showStub('GitHub Repository', 'ML Project GitHub'),
      },
    ],
  },
]

export const FAVORITES = [
  { id: 'projects', name: 'Projects', icon: '📁', path: [] },
  { id: 'documents', name: 'Documents', icon: '📄', path: ['documents'] },
  { id: 'downloads', name: 'Downloads', icon: '⬇️', path: ['downloads'] },
  { id: 'desktop', name: 'Desktop', icon: '🖥️', path: ['desktop'] },
]
