import { type Project } from '../types/finder'

export const PROJECTS_DATA: Project[] = [
  {
    id: 'portfolio-project',
    name: 'Portfolio Project',
    type: 'folder',
    icon: '💼',
    children: [
      {
        id: 'frontend',
        name: 'Frontend',
        type: 'folder',
        icon: '⚛️',
        children: [
          {
            id: 'components',
            name: 'Components',
            type: 'folder',
            icon: '🧩',
            children: [],
          },
          {
            id: 'pages',
            name: 'Pages',
            type: 'folder',
            icon: '📄',
            children: [],
          },
          {
            id: 'widgets',
            name: 'Widgets',
            type: 'folder',
            icon: '🎨',
            children: [],
          },
        ],
      },
      {
        id: 'backend',
        name: 'Backend',
        type: 'folder',
        icon: '🔧',
        children: [
          {
            id: 'gateway',
            name: 'Gateway',
            type: 'folder',
            icon: '🚪',
            children: [],
          },
          {
            id: 'connections',
            name: 'Connections',
            type: 'folder',
            icon: '🔗',
            children: [],
          },
          {
            id: 'projects',
            name: 'Projects',
            type: 'folder',
            icon: '📁',
            children: [],
          },
          {
            id: 'modules',
            name: 'Modules',
            type: 'folder',
            icon: '🧩',
            children: [],
          },
          {
            id: 'admin',
            name: 'Admin',
            type: 'folder',
            icon: '⚙️',
            children: [],
          },
        ],
      },
      {
        id: 'infrastructure',
        name: 'Infrastructure',
        type: 'folder',
        icon: '🏗️',
        children: [
          {
            id: 'docker',
            name: 'Docker',
            type: 'folder',
            icon: '🐳',
            children: [],
          },
          {
            id: 'nginx',
            name: 'Nginx',
            type: 'folder',
            icon: '🌐',
            children: [],
          },
          {
            id: 'postgres',
            name: 'PostgreSQL',
            type: 'folder',
            icon: '🗄️',
            children: [],
          },
        ],
      },
      {
        id: 'readme',
        name: 'README.md',
        type: 'file',
        icon: '📝',
        fileType: 'readme',
        url: 'https://example.com/readme.md',
      },
      {
        id: 'architecture',
        name: 'Architecture',
        type: 'file',
        icon: '📊',
        fileType: 'architecture',
        url: 'https://example.com/architecture.excalidraw',
      },
      {
        id: 'demo',
        name: 'Demo',
        type: 'file',
        icon: '🌐',
        fileType: 'demo',
        url: 'https://example.com/demo',
      },
      {
        id: 'github',
        name: 'GitHub',
        type: 'file',
        icon: '👨‍💻',
        fileType: 'github',
        url: 'https://github.com/iizhukov/portfolio',
      },
      {
        id: 'database',
        name: 'Database',
        type: 'file',
        icon: '🗃️',
        fileType: 'database',
        url: 'https://example.com/database.dbml',
      },
      {
        id: 'swagger',
        name: 'Swagger',
        type: 'file',
        icon: '📋',
        fileType: 'swagger',
        url: 'https://example.com/swagger.json',
      },
    ],
  },
]

export const FAVORITES = [
  { id: 'projects', name: 'Projects', icon: '📁', path: [] },
  { id: 'documents', name: 'Documents', icon: '📄', path: ['documents'] },
  { id: 'downloads', name: 'Downloads', icon: '⬇️', path: ['downloads'] },
  { id: 'desktop', name: 'Desktop', icon: '🖥️', path: ['desktop'] },
]
